# -*- coding: utf-8 -*-
"""data_ex.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dQezl1kVJP00jLnyRi9c3BKYhcfUlYih
"""

query = f"""
SELECT
    p.subject_id,
    p.gender,
    ice.stay_id,
    ice.hadm_id,
    a.hospital_expire_flag as outcome
FROM `{MIMIC_PROJECT}.{MIMIC_DATASET_HOSP}.patients` p
INNER JOIN `{MIMIC_PROJECT}.{MIMIC_DATASET_ICU}.icustays` ice
    ON p.subject_id = ice.subject_id
INNER JOIN `{MIMIC_PROJECT}.{MIMIC_DATASET_HOSP}.admissions` a
    ON ice.hadm_id = a.hadm_id
ORDER BY p.subject_id, ice.intime
"""

print("Fetching data from MIMIC-IV...")
df = client.query(query).to_dataframe()

print(f"\nRetrieved {len(df):,} ICU visits")
print("\nSample of data:")
display(HTML(df.head(20).to_html(index=False)))

# Show summary
print("Summary by Gender and Outcome:")
summary = df.groupby(['gender', 'outcome']).size().reset_index(name='count')
display(HTML(summary.to_html(index=False)))

# Save to CSV
df.to_csv('gender_outcome_table.csv', index=False)
print(f"\nTable saved to: gender_outcome_table.csv")